java_library(
    name = "handlers",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/main/com/fun/server:__pkg__",
        "//src/test/com/fun/handlers:__pkg__",
    ],
    deps = [
        "//src/main/com/fun/messages",
    ],
)
