java_test(
    name = "MessageTest",
    srcs = [
        "MessageTest.java",
    ],
    test_class = "com.fun.messages.MessageTest",
    deps = [
        "//:java_test_deps",
        "//src/main/com/fun/messages",
    ],
)
