java_test(
    name = "MyHttpHandlerTest",
    size = "small",
    srcs = [
        "MyHttpHandlerTest.java",
    ],
    test_class = "com.fun.handlers.MyHttpHandlerTest",
    deps = [
        "//:java_test_deps",
        "//src/main/com/fun/handlers",
        "//src/main/com/fun/messages",
    ],
)
